# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('info', models.TextField()),
                ('collection', models.CharField(blank=True, max_length=32, null=True)),
                ('posted_on', models.DateTimeField(default=datetime.datetime(2017, 4, 4, 20, 56, 5, 899000))),
                ('slug', models.SlugField()),
            ],
        ),
    ]
